name: E2E tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install
      run: npm install 
    - name: Run e2e tests
      uses: DevExpress/testcafe-action@latest
      with:
        args: chrome ./e2e/*.js --app "npm start"
