name: Node CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install
      run: npm install      
    - name: test
      run: npm test --ci
      env:
        CI: true
